apiVersion: apps/v1
kind: Deployment
metadata:
  name: udacity-capstone
spec:
  replicas: 3
  selector:
    matchLabels:
      app: udacity-capstone
  template:
    metadata:
      labels:
        app: udacity-capstone
    spec:
      containers:
      - name: udacity-capstone
        image: vuthaiminh98/minhvt9:master
        imagePullPolicy: Always
      imagePullSecrets: vuthaiminh98
        ports:
        - containerPort: 9090
          name: default-port
